---
title: "Estadisticas policiales 2021"
author: "Ashley Jump Bustamante"
date: '2022-06-14'
output: html_document
---

### Tabla de datos

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)
library(plotly)
library(readr)
library(dplyr)
library(DT)

```

```{r Carga de datos}
Datos_policiales <- readxl::read_excel("C:/Users/50685/Desktop/Prosesamiento de datos/Tarea 2/Estadisticas_judiciales_2021/estadisticaspoliciales2021.xls")
```

```{r Transformacion de datos, message=FALSE, echo=FALSE}
Datos_policiales <-
 Datos_policiales %>%
  mutate(Mes = format(Fecha, "%B"))%>%
  select(Delito, Fecha, Victima, Edad, Genero, Provincia, Canton, Mes)%>%
  mutate(Fecha = as.Date(Fecha, format = "%d/%m/%Y"))
```


## Entrada

### DT con las columnas de Delito, Fecha, Víctima, Edad, Género, Provincia y Cantón.

```{r Visualización de datos nacionales policiales en formato tabular}
Datos_policiales %>%
   datatable(options = list(
    pageLength = 25,
    language = list(url = '//cdn.datatables.net/plug-ins/1.10.11/i18n/Spanish.json')
  ))
```

## Gráficos

### Gráficos de barras simples

#### Por tipo de delito

```{r Gráfico por tipo de delito}
Grafico_tipo_delito <-
  Datos_policiales %>%
  ggplot(aes(x = Delito)) +
  geom_bar(width = 0.8) +
  ggtitle("Cantidad de delitos por tipo de delito") +
  xlab("Delito") +
  ylab("Frecuencia") +
  coord_flip() +
  theme_minimal()

ggplotly(Grafico_tipo_delito) %>% config(locale = 'es')
```

#### Por mes del año
```{r Gráfico por mes del año}
Grafico_por_mes <-
  Datos_policiales %>% 
  ggplot(aes(x = Mes)) +
  geom_bar( ) + 
  ggtitle("Cantidad de delitos por Mes") +
  xlab("Meses") +
  ylab("Cantidad de Delitos") +
  coord_flip() +
  theme_minimal()

ggplotly(Grafico_por_mes) %>% config(locale = 'es')
```

#### Por cantones

```{r Gráfico por cantones}
Grafico_provincias <- filter(Datos_policiales, grepl("SAN JOSE|ALAJUELA|CARTAGO|HEREDIA", Canton))

Delitos_por_provincia <- 
  ggplot(data= Grafico_provincias, aes(x= Canton)) +
  geom_bar(width = 0.8) +
  ggtitle("Cantidad de delitos en San José, Alajuela, Cartago y Heredia") +
  xlab("Provincia") +
  ylab("Cantidad de delitos") +
  coord_flip() +
  theme_minimal()

ggplotly(Delitos_por_provincia) %>% config(locale = 'es')
```

### Gráfico de barras apiladas

#### Por género

```{r Gráfico por género}
Grafico_por_genero <-
  Datos_policiales %>%
  ggplot(aes(x = Delito, fill = Genero)) +
  geom_bar(position = "fill", width = 0.60) +
  ggtitle("Proporción de delitos por género") +
  xlab("Delito") +
  ylab("Género") +
  labs(fill = "Género") +
   coord_flip() +
  theme_minimal()

ggplotly(Grafico_por_genero) %>% config(locale = 'es')
```
